/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package puenteestrechoumg;

import java.awt.Image;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;

/**
 *
 * @author David Mencos
 */
public class Main extends javax.swing.JFrame {
    
    // Referencia estatica al GUI
    static Main gui = new Main();
    
    // Numero máximo de carros que pueden usar el puente simultaneamente
    public static int MAX_CARROS = 3;
    
    // Array de imagenes para el puente
    ImageIcon imagenPuente[];
    
    // Variables indicadoras del monitor de paso para el puente
    private int numeroCarros = 0; // Cantidad de carros que estan utilizando el puente
    private int direccionActual = 0; // 0 es hacia abajo y 1 es hacia arriba
    private int[] colaEspera = { 0, 0}; // Cantidad de carros que se encuentran en espera en cada lado ~ 0 es abajo y 1 es arriba

    // Obtiene el numero de carros que actualmente están cruzando el puente
    public int obtenerNumeroCarros() {
        return numeroCarros;
    }

    public void incrementarNumeroCarros() {
        this.numeroCarros++;
        this.lblCarrosPuente.setText(String.valueOf(this.numeroCarros));
        System.out.println("AUMENTA Carros en Puente: " + this.numeroCarros);
    }

    public void decrecerNumeroCarros() {
        this.numeroCarros--;
        this.lblCarrosPuente.setText(String.valueOf(this.numeroCarros));
        System.out.println("DECRECE Carros en Puente: " + this.numeroCarros);
    }
    
    public void cambiarImagenPuente(int direccion){
        this.lblPuente.setIcon(imagenPuente[direccion]);
    }
    
    public int obtenerDireccionActual() {
        //System.out.println("Direccion actual: " + this.direccionActual);
        return direccionActual;
    }

    public void cambiarDireccionActual(int direccionActual) {
        this.direccionActual = direccionActual;
        System.out.println("CAMBIADA Direccion Actual: " + this.direccionActual);
    }
    
    public int obtenerColaEspera(int direccionActual) {
        System.out.println("Cola de espera para direccion " + direccionActual +": " + this.colaEspera[direccionActual]);
        return this.colaEspera[direccionActual];
    }
    
    public void incrementarColaEspera(int direccionActual) {
        this.colaEspera[direccionActual]++;
        switch(direccionActual){
            case 0:
                this.lblNumeroCarros1.setText(String.valueOf(this.colaEspera[direccionActual]));
                break;
            case 1:
                this.lblNumeroCarros0.setText(String.valueOf(this.colaEspera[direccionActual]));
                break;
            default:
                break;
        }
        System.out.println("AUMENTA Cola Espera en Direccion " + direccionActual +" : " + this.colaEspera[direccionActual]);
    }
    
    public void decrecerColaEspera(int direccionActual) {
        this.colaEspera[direccionActual]--;
        switch(direccionActual){
            case 0:
                this.lblNumeroCarros1.setText(String.valueOf(this.colaEspera[direccionActual]));
                break;
            case 1:
                this.lblNumeroCarros0.setText(String.valueOf(this.colaEspera[direccionActual]));
                break;
            default:
                break;
        }
        System.out.println("DECRECE Cola Espera en Direccion " + direccionActual +" : " + this.colaEspera[direccionActual]);
    }
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        imagenPuente = new ImageIcon[2];
        imagenPuente[0] = new ImageIcon(new ImageIcon("Resources\\bridge2.png").getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH));
        imagenPuente[1] = new ImageIcon(new ImageIcon("Resources\\bridge1.png").getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuente = new javax.swing.JLabel();
        lblCarro1 = new javax.swing.JLabel();
        lblCarro2 = new javax.swing.JLabel();
        lblNumeroCarros0 = new javax.swing.JLabel();
        lblNumeroCarros1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblCarrosPuente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblPuente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bridge0.png"))); // NOI18N

        lblCarro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/car01.png"))); // NOI18N
        lblCarro1.setText("jLabel1");

        lblCarro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/car02.png"))); // NOI18N
        lblCarro2.setText("jLabel1");

        lblNumeroCarros0.setBackground(java.awt.Color.white);
        lblNumeroCarros0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroCarros0.setText("0");

        lblNumeroCarros1.setBackground(java.awt.Color.white);
        lblNumeroCarros1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroCarros1.setText("0");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        lblCarrosPuente.setBackground(java.awt.Color.white);
        lblCarrosPuente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarrosPuente.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumeroCarros0, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPuente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCarrosPuente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lblNumeroCarros1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCarro2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnIniciar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarro2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroCarros1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblPuente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCarrosPuente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroCarros0, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        Monitor monitor = new Monitor();
        monitor.start();
        
        Carro[] hilos = new Carro[12];
        
        for(int i = 0; i < 12; i++){
            hilos[i] = new Carro();
            hilos[i].start();
            try{
                sleep(250);
            }catch(InterruptedException e){}
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblCarro1;
    private javax.swing.JLabel lblCarro2;
    private javax.swing.JLabel lblCarrosPuente;
    private javax.swing.JLabel lblNumeroCarros0;
    private javax.swing.JLabel lblNumeroCarros1;
    private javax.swing.JLabel lblPuente;
    // End of variables declaration//GEN-END:variables
}
